# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g pnpm
    pnpm install
    pnpm build
    tar zcvf ./example/dist.tar.gz ./example/dist
  displayName: 'PNPM install and build'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: TencentCloud
    contents: './example/dist.tar.gz'
    targetFolder: '/tmp'
    readyTimeout: '20000'
    overwrite: true
  displayName: 'Copy files to the remote machine'

- task: SSH@0
  inputs:
    sshEndpoint: TencentCloud
    runOptions: 'inline'
    inline: |
      tar -zxvf /tmp/example/dist.tar.gz -C /tmp
      rm -rf $(DEPLOY_DIR)/vue3-amap /tmp/example
      mv /tmp/dist $(DEPLOY_DIR)/vue3-amap
  displayName: 'Deploy'